"""The three generators. Each is a ``name`` and a ``generate(ctx)`` returning files.

Everything emitted is laid out the way ``ruff format`` leaves it -- one item to a line
behind a trailing comma -- so the committed output passes the project's own formatter
whatever line length it is set to, and a regeneration is a diff of the lines that moved.
"""

from __future__ import annotations

import json

from metaobjects.codegen.generator import EmittedFile

from . import model


def _header(generator: str) -> str:
    return (
        f"# @generated by metaobjects (metagen:{generator}) from the model in metaobjects/.\n"
        "# Do not edit: change the metadata and regenerate. A hand edit fails\n"
        "# `metaobjects verify --codegen`.\n"
    )


def _string(value: str) -> str:
    if '"' in value and "'" not in value:
        return repr(value)
    return json.dumps(value, ensure_ascii=False)


def _literal(value, depth: int = 0) -> str:
    """A tuple, a dict or a string, as the formatter would leave it."""
    pad, end = "    " * (depth + 1), "    " * depth
    if isinstance(value, dict):
        if not value:
            return "{}"
        items = (f"{pad}{_string(k)}: {_literal(v, depth + 1)},\n" for k, v in value.items())
        return "{\n" + "".join(items) + end + "}"
    if isinstance(value, tuple):
        if not value:
            return "()"
        if len(value) == 1:
            return f"({_literal(value[0], depth)},)"
        return "(\n" + "".join(f"{pad}{_literal(v, depth + 1)},\n" for v in value) + end + ")"
    return _string(value)


def _assign(name: str, value) -> str:
    return f"{name} = {_literal(value)}\n"


class Rows:
    name = "metagen-rows"

    def generate(self, ctx):
        rows = model.rows(ctx.loaded_root)
        content = (
            _header("rows")
            + '"""The rows this tool prints: the columns each offers, and what each one reads.\n'
            "\n"
            "``FIELDS`` is every column a row can carry, in the order they are documented and\n"
            "printed. ``DEFAULT`` is the set shown when no columns are asked for. ``READS`` is\n"
            "the attributes of the upstream object that each column is read from: nothing at\n"
            "run time reads it, and it is here so that what a column is made of ships with\n"
            'the column, for the test suite and for whatever builds on this package.\n"""\n'
            "\n"
            "from __future__ import annotations\n"
            "\n"
            + _assign("FIELDS", {row.key: tuple(row.reads) for row in rows})
            + "\n"
            + _assign("DEFAULT", {row.key: row.default for row in rows})
            + "\n"
            + _assign("READS", {row.key: row.reads for row in rows})
        )
        return [EmittedFile(path="rows.py", content=content)]


_ELEMENT = """

def _element(kind: str, attributes: dict) -> dict:
    unknown = sorted(set(attributes) - set(ATTRIBUTES[kind]))
    if unknown:
        raise KeyError(
            f"{kind}: {unknown} is not an attribute the model declares, and a double may "
            "not invent one; declare it, and the capture check will say whether a real "
            "server sends it"
        )
    absent = [name for name in REQUIRED[kind] if attributes.get(name) in (None, "")]
    if absent:
        raise KeyError(f"{kind}: a real {ELEMENT[kind]} element always carries {absent}")
    return attributes
"""


class Elements:
    name = "metagen-elements"

    def generate(self, ctx):
        objects = model.upstream(ctx.loaded_root)
        content = (
            _header("elements")
            + '"""Builders for the answers a test double gives in place of the real server.\n'
            "\n"
            "One function per declared object. Each takes the attributes of one element by\n"
            "the server's own names and hands them back in the order given, having refused\n"
            "a name the model does not declare and the absence of one a real element always\n"
            'carries. A double that builds every answer through these cannot invent a name.\n"""\n'
            "\n"
            "from __future__ import annotations\n"
            "\n"
            + _assign("ELEMENT", {entry.key: entry.element for entry in objects})
            + "\n"
            + _assign("ATTRIBUTES", {entry.key: entry.fields for entry in objects})
            + "\n"
            + _assign("REQUIRED", {entry.key: entry.required for entry in objects})
            + _ELEMENT
        )
        for entry in objects:
            content += (
                f"\n\ndef {entry.key}(**attributes) -> dict:\n"
                f'    """The attributes of one {entry.element} element, as {entry.fqn} declares them."""\n'
                f'    return _element("{entry.key}", attributes)\n'
            )
        return [EmittedFile(path="elements.py", content=content)]


_CONTRACT = '''

def _capture() -> Path:
    """The capture, found from here: this file may be generated into any directory."""
    for parent in Path(__file__).resolve().parents:
        if (parent / CAPTURE_FILE).is_file():
            return parent / CAPTURE_FILE
    raise FileNotFoundError(f"no {CAPTURE_FILE} above {__file__}")


#: Why an attribute could not be observed, by the object's short name.
UNOBSERVED = {
    entry["key"]: entry["unobserved"] for entry in DECLARED.values() if entry["unobserved"]
}


def answers(path=None) -> dict:
    """The captured answers: the attribute names each one carried."""
    return json.loads(Path(path or _capture()).read_text(encoding="utf-8"))["elements"]


def never_sent(elements: dict, declared: dict = DECLARED) -> dict:
    """Declared attributes that no captured answer carries and no reason excuses."""
    found = {}
    for fqn, entry in declared.items():
        seen = set().union(*(elements.get(name, ()) for name in entry["capture"]))
        missing = sorted(set(entry["fields"]) - seen - set(entry["unobserved"]))
        if missing:
            found[fqn] = missing
    return found


def never_read(elements: dict, rows: dict = ROWS, declared: dict = DECLARED) -> dict:
    """Attributes a row reads that an answer it is built from never carries."""
    found = {}
    for key, row in rows.items():
        excused = set(declared[row["of"]]["unobserved"])
        for name in row["capture"]:
            missing = sorted(set(row["reads"]) - set(elements.get(name, ())) - excused)
            if missing:
                found[f"{key} row, from {name}"] = missing
    return found


def undeclared(elements: dict, declared: dict = DECLARED) -> dict:
    """What the server sends and the model does not declare. Reported, never a failure."""
    found = {}
    for fqn, entry in declared.items():
        seen = set().union(*(elements.get(name, ()) for name in entry["capture"]))
        found[fqn] = sorted(seen - set(entry["fields"]))
    return found


def outlived(elements: dict, declared: dict = DECLARED) -> dict:
    """Reasons kept for an attribute a captured answer does carry. Reported only."""
    found = {}
    for fqn, entry in declared.items():
        seen = set().union(*(elements.get(name, ()) for name in entry["capture"]))
        stale = sorted(set(entry["unobserved"]) & seen)
        if stale:
            found[fqn] = stale
    return found


def report(elements: dict) -> str:
    """Both directions, in words: the one that fails and the one that only informs."""
    lines = []
    for fqn, extra in undeclared(elements).items():
        entry = DECLARED[fqn]
        lines.append(
            f"{fqn}: declares {len(entry['fields'])} attributes, "
            f"{len(entry['unobserved'])} of them with a reason they were not observed; "
            f"the captured server sends {len(extra)} more, which are not declared"
        )
        if extra:
            lines.append("  not declared: " + ", ".join(extra))
    for fqn, stale in outlived(elements).items():
        lines.append(f"{fqn}: a reason is kept for {stale}, which the capture now carries")
    failures = {**never_sent(elements), **never_read(elements)}
    for where, missing in failures.items():
        lines.append(f"FAIL {where}: {missing} is in no captured answer and has no reason")
    lines.append("capture check: " + ("FAILED" if failures else "passed"))
    return "\\n".join(lines) + "\\n"


if __name__ == "__main__":
    captured = answers()
    sys.stdout.write(report(captured))
    sys.exit(1 if never_sent(captured) or never_read(captured) else 0)
'''

_CONTRACT_TEST = """
from __future__ import annotations

import pytest

from . import capture_contract as contract

ELEMENTS = contract.answers()


@pytest.mark.parametrize("fqn", sorted(contract.DECLARED))
def test_every_declared_attribute_is_one_a_real_server_sent(fqn):
    missing = contract.never_sent(ELEMENTS, {fqn: contract.DECLARED[fqn]})
    assert missing == {}, (
        f"{missing} is declared and no captured answer carries it: it was invented, or it "
        "needs an `unobserved` reason saying why the capture could not have seen it"
    )


@pytest.mark.parametrize("key", sorted(contract.ROWS))
def test_every_attribute_a_row_reads_is_in_each_answer_it_is_built_from(key):
    missing = contract.never_read(ELEMENTS, {key: contract.ROWS[key]})
    assert missing == {}, f"{missing}: the column is empty everywhere but in the tests"
"""


class CaptureContract:
    name = "metagen-capture-contract"

    def generate(self, ctx):
        root = ctx.loaded_root
        objects, rows = model.upstream(root), model.rows(root)
        declared = {
            entry.fqn: {
                "key": entry.key,
                "capture": entry.capture,
                "fields": entry.fields,
                "unobserved": entry.unobserved,
            }
            for entry in objects
        }
        reads = {
            row.key: {
                "of": row.of,
                "capture": row.capture,
                "reads": tuple(sorted({name for names in row.reads.values() for name in names})),
            }
            for row in rows
        }
        contract = (
            _header("capture_contract")
            + '"""What the model declares, held to a committed capture of a real server.\n'
            "\n"
            "It fails in one direction: an attribute that is declared, is in no captured\n"
            "answer, and carries no reason it could not be observed. That is an invented\n"
            "name, and whatever reads it is empty on every real server. The other direction\n"
            "is reported and never failed: a server sends far more than a tool reads, and\n"
            "the model declares what is read.\n"
            "\n"
            "Run this file to print both directions. The standard library is all it needs.\n"
            '"""\n'
            "\n"
            "from __future__ import annotations\n"
            "\n"
            "import json\n"
            "import sys\n"
            "from pathlib import Path\n"
            "\n"
            "#: The committed capture, as a path from the project root.\n"
            f"CAPTURE_FILE = {_string(model.capture_file(root))}\n"
            "\n"
            "#: Each declared object: the captured answers that show it, its attributes, and\n"
            "#: the reason for any that no capture could have seen.\n"
            + _assign("DECLARED", declared)
            + "\n"
            "#: Each row: the object it is read from, the answers it is built from, and the\n"
            "#: attributes it reads.\n" + _assign("ROWS", reads) + _CONTRACT
        )
        test = (
            _header("capture_contract")
            + '"""The capture check, as tests: see ``capture_contract`` beside this file."""\n'
            + _CONTRACT_TEST
        )
        return [
            EmittedFile(path="capture_contract.py", content=contract),
            EmittedFile(path="test_capture_contract.py", content=test),
        ]


rows, elements, capture_contract = Rows(), Elements(), CaptureContract()
