# @generated by metaobjects (metagen:rows) from the model in metaobjects/.
# Do not edit: change the metadata and regenerate. A hand edit fails
# `metaobjects verify --codegen`.
"""The rows this tool prints: the columns each offers, and what each one reads.

``FIELDS`` is every column a row can carry, in the order they are documented and
printed. ``DEFAULT`` is the set shown when no columns are asked for. ``READS`` is
the attributes of the upstream object that each column is read from: nothing at
run time reads it, and it is here so that what a column is made of ships with
the column, for the test suite and for whatever builds on this package.
"""

from __future__ import annotations

FIELDS = {
    "track": (
        "key",
        "media_id",
        "title",
        "artist",
        "track_artist",
        "album",
        "year",
        "rating",
        "duration",
        "plays",
        "skips",
        "index",
        "added",
        "guid",
    ),
    "similar": (
        "key",
        "media_id",
        "title",
        "artist",
        "track_artist",
        "album",
        "year",
        "rating",
        "duration",
        "plays",
        "skips",
        "index",
        "added",
        "guid",
        "distance",
    ),
    "album": (
        "key",
        "media_id",
        "title",
        "artist",
        "year",
        "rating",
        "added",
        "guid",
    ),
    "artist": (
        "key",
        "media_id",
        "title",
        "rating",
        "added",
        "guid",
    ),
    "playlist": (
        "key",
        "media_id",
        "title",
        "smart",
        "items",
        "updated",
    ),
}

DEFAULT = {
    "track": (
        "key",
        "media_id",
        "title",
        "artist",
    ),
    "similar": (
        "distance",
        "key",
        "media_id",
        "title",
    ),
    "album": (
        "key",
        "media_id",
        "title",
        "artist",
    ),
    "artist": (
        "key",
        "media_id",
        "title",
    ),
    "playlist": (
        "key",
        "media_id",
        "title",
        "smart",
    ),
}

READS = {
    "track": {
        "key": ("ratingKey",),
        "media_id": ("ratingKey",),
        "title": ("title",),
        "artist": ("grandparentTitle",),
        "track_artist": (
            "grandparentTitle",
            "originalTitle",
        ),
        "album": ("parentTitle",),
        "year": ("parentYear",),
        "rating": ("userRating",),
        "duration": ("duration",),
        "plays": ("viewCount",),
        "skips": ("skipCount",),
        "index": ("index",),
        "added": ("addedAt",),
        "guid": ("guid",),
    },
    "similar": {
        "key": ("ratingKey",),
        "media_id": ("ratingKey",),
        "title": ("title",),
        "artist": ("grandparentTitle",),
        "track_artist": (
            "grandparentTitle",
            "originalTitle",
        ),
        "album": ("parentTitle",),
        "year": ("parentYear",),
        "rating": ("userRating",),
        "duration": ("duration",),
        "plays": ("viewCount",),
        "skips": ("skipCount",),
        "index": ("index",),
        "added": ("addedAt",),
        "guid": ("guid",),
        "distance": ("distance",),
    },
    "album": {
        "key": ("ratingKey",),
        "media_id": ("ratingKey",),
        "title": ("title",),
        "artist": ("parentTitle",),
        "year": ("year",),
        "rating": ("userRating",),
        "added": ("addedAt",),
        "guid": ("guid",),
    },
    "artist": {
        "key": ("ratingKey",),
        "media_id": ("ratingKey",),
        "title": ("title",),
        "rating": ("userRating",),
        "added": ("addedAt",),
        "guid": ("guid",),
    },
    "playlist": {
        "key": ("ratingKey",),
        "media_id": ("ratingKey",),
        "title": ("title",),
        "smart": ("smart",),
        "items": ("leafCount",),
        "updated": ("updatedAt",),
    },
}
