# @generated by metaobjects (metagen:capture_contract) from the model in metaobjects/.
# Do not edit: change the metadata and regenerate. A hand edit fails
# `metaobjects verify --codegen`.
"""What the model declares, held to a committed capture of a real server.

It fails in one direction: an attribute that is declared, is in no captured
answer, and carries no reason it could not be observed. That is an invented
name, and whatever reads it is empty on every real server. The other direction
is reported and never failed: a server sends far more than a tool reads, and
the model declares what is read.

Run this file to print both directions. The standard library is all it needs.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

#: The committed capture, as a path from the project root.
CAPTURE_FILE = "tests/fixtures/plex-shape/capture.json"

#: Each declared object: the captured answers that show it, its attributes, and
#: the reason for any that no capture could have seen.
DECLARED = {
    "plex::library::Track": {
        "key": "track",
        "capture": (
            "track.row",
            "track.detail",
            "playlist.item",
        ),
        "fields": (
            "ratingKey",
            "key",
            "guid",
            "type",
            "title",
            "titleSort",
            "originalTitle",
            "parentRatingKey",
            "parentTitle",
            "parentIndex",
            "parentYear",
            "grandparentRatingKey",
            "grandparentTitle",
            "index",
            "duration",
            "userRating",
            "viewCount",
            "skipCount",
            "addedAt",
            "lastViewedAt",
            "musicAnalysisVersion",
            "distance",
            "playlistItemID",
        ),
        "unobserved": {
            "musicAnalysisVersion": "sonic analysis was off for the captured library",
            "distance": "only on `/nearest`, which answers nothing with analysis off",
        },
    },
    "plex::library::Album": {
        "key": "album",
        "capture": (
            "album.row",
            "album.detail",
        ),
        "fields": (
            "ratingKey",
            "key",
            "guid",
            "type",
            "title",
            "titleSort",
            "parentRatingKey",
            "parentTitle",
            "parentGuid",
            "year",
            "leafCount",
            "userRating",
            "addedAt",
            "studio",
            "summary",
        ),
        "unobserved": {
            "userRating": "sent only on a rated item, and no album in the sample was rated",
        },
    },
    "plex::library::Artist": {
        "key": "artist",
        "capture": (
            "artist.row",
            "artist.detail",
        ),
        "fields": (
            "ratingKey",
            "key",
            "guid",
            "type",
            "title",
            "titleSort",
            "summary",
            "userRating",
            "addedAt",
            "librarySectionID",
        ),
        "unobserved": {},
    },
    "plex::library::Playlist": {
        "key": "playlist",
        "capture": ("playlist",),
        "fields": (
            "ratingKey",
            "key",
            "guid",
            "type",
            "title",
            "titleSort",
            "summary",
            "smart",
            "playlistType",
            "composite",
            "duration",
            "leafCount",
            "addedAt",
            "updatedAt",
        ),
        "unobserved": {},
    },
}

#: Each row: the object it is read from, the answers it is built from, and the
#: attributes it reads.
ROWS = {
    "track": {
        "of": "plex::library::Track",
        "capture": (
            "track.row",
            "playlist.item",
        ),
        "reads": (
            "addedAt",
            "duration",
            "grandparentTitle",
            "guid",
            "index",
            "originalTitle",
            "parentTitle",
            "parentYear",
            "ratingKey",
            "skipCount",
            "title",
            "userRating",
            "viewCount",
        ),
    },
    "similar": {
        "of": "plex::library::Track",
        "capture": (),
        "reads": (
            "addedAt",
            "distance",
            "duration",
            "grandparentTitle",
            "guid",
            "index",
            "originalTitle",
            "parentTitle",
            "parentYear",
            "ratingKey",
            "skipCount",
            "title",
            "userRating",
            "viewCount",
        ),
    },
    "album": {
        "of": "plex::library::Album",
        "capture": ("album.row",),
        "reads": (
            "addedAt",
            "guid",
            "parentTitle",
            "ratingKey",
            "title",
            "userRating",
            "year",
        ),
    },
    "artist": {
        "of": "plex::library::Artist",
        "capture": ("artist.row",),
        "reads": (
            "addedAt",
            "guid",
            "ratingKey",
            "title",
            "userRating",
        ),
    },
    "playlist": {
        "of": "plex::library::Playlist",
        "capture": ("playlist",),
        "reads": (
            "leafCount",
            "ratingKey",
            "smart",
            "title",
            "updatedAt",
        ),
    },
}


def _capture() -> Path:
    """The capture, found from here: this file may be generated into any directory."""
    for parent in Path(__file__).resolve().parents:
        if (parent / CAPTURE_FILE).is_file():
            return parent / CAPTURE_FILE
    raise FileNotFoundError(f"no {CAPTURE_FILE} above {__file__}")


#: Why an attribute could not be observed, by the object's short name.
UNOBSERVED = {
    entry["key"]: entry["unobserved"] for entry in DECLARED.values() if entry["unobserved"]
}


def answers(path=None) -> dict:
    """The captured answers: the attribute names each one carried."""
    return json.loads(Path(path or _capture()).read_text(encoding="utf-8"))["elements"]


def never_sent(elements: dict, declared: dict = DECLARED) -> dict:
    """Declared attributes that no captured answer carries and no reason excuses."""
    found = {}
    for fqn, entry in declared.items():
        seen = set().union(*(elements.get(name, ()) for name in entry["capture"]))
        missing = sorted(set(entry["fields"]) - seen - set(entry["unobserved"]))
        if missing:
            found[fqn] = missing
    return found


def never_read(elements: dict, rows: dict = ROWS, declared: dict = DECLARED) -> dict:
    """Attributes a row reads that an answer it is built from never carries."""
    found = {}
    for key, row in rows.items():
        excused = set(declared[row["of"]]["unobserved"])
        for name in row["capture"]:
            missing = sorted(set(row["reads"]) - set(elements.get(name, ())) - excused)
            if missing:
                found[f"{key} row, from {name}"] = missing
    return found


def undeclared(elements: dict, declared: dict = DECLARED) -> dict:
    """What the server sends and the model does not declare. Reported, never a failure."""
    found = {}
    for fqn, entry in declared.items():
        seen = set().union(*(elements.get(name, ()) for name in entry["capture"]))
        found[fqn] = sorted(seen - set(entry["fields"]))
    return found


def outlived(elements: dict, declared: dict = DECLARED) -> dict:
    """Reasons kept for an attribute a captured answer does carry. Reported only."""
    found = {}
    for fqn, entry in declared.items():
        seen = set().union(*(elements.get(name, ()) for name in entry["capture"]))
        stale = sorted(set(entry["unobserved"]) & seen)
        if stale:
            found[fqn] = stale
    return found


def report(elements: dict) -> str:
    """Both directions, in words: the one that fails and the one that only informs."""
    lines = []
    for fqn, extra in undeclared(elements).items():
        entry = DECLARED[fqn]
        lines.append(
            f"{fqn}: declares {len(entry['fields'])} attributes, "
            f"{len(entry['unobserved'])} of them with a reason they were not observed; "
            f"the captured server sends {len(extra)} more, which are not declared"
        )
        if extra:
            lines.append("  not declared: " + ", ".join(extra))
    for fqn, stale in outlived(elements).items():
        lines.append(f"{fqn}: a reason is kept for {stale}, which the capture now carries")
    failures = {**never_sent(elements), **never_read(elements)}
    for where, missing in failures.items():
        lines.append(f"FAIL {where}: {missing} is in no captured answer and has no reason")
    lines.append("capture check: " + ("FAILED" if failures else "passed"))
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    captured = answers()
    sys.stdout.write(report(captured))
    sys.exit(1 if never_sent(captured) or never_read(captured) else 0)
