# @generated by metaobjects (metagen:elements) from the model in metaobjects/.
# Do not edit: change the metadata and regenerate. A hand edit fails
# `metaobjects verify --codegen`.
"""Builders for the answers a test double gives in place of the real server.

One function per declared object. Each takes the attributes of one element by
the server's own names and hands them back in the order given, having refused
a name the model does not declare and the absence of one a real element always
carries. A double that builds every answer through these cannot invent a name.
"""

from __future__ import annotations

ELEMENT = {
    "track": "Track",
    "album": "Directory",
    "artist": "Directory",
    "playlist": "Playlist",
}

ATTRIBUTES = {
    "track": (
        "ratingKey",
        "key",
        "guid",
        "type",
        "title",
        "titleSort",
        "originalTitle",
        "parentRatingKey",
        "parentTitle",
        "parentIndex",
        "parentYear",
        "grandparentRatingKey",
        "grandparentTitle",
        "index",
        "duration",
        "userRating",
        "viewCount",
        "skipCount",
        "addedAt",
        "lastViewedAt",
        "musicAnalysisVersion",
        "distance",
        "playlistItemID",
    ),
    "album": (
        "ratingKey",
        "key",
        "guid",
        "type",
        "title",
        "titleSort",
        "parentRatingKey",
        "parentTitle",
        "parentGuid",
        "year",
        "leafCount",
        "userRating",
        "addedAt",
        "studio",
        "summary",
    ),
    "artist": (
        "ratingKey",
        "key",
        "guid",
        "type",
        "title",
        "titleSort",
        "summary",
        "userRating",
        "addedAt",
        "librarySectionID",
    ),
    "playlist": (
        "ratingKey",
        "key",
        "guid",
        "type",
        "title",
        "titleSort",
        "summary",
        "smart",
        "playlistType",
        "composite",
        "duration",
        "leafCount",
        "addedAt",
        "updatedAt",
    ),
}

REQUIRED = {
    "track": (
        "ratingKey",
        "type",
        "title",
    ),
    "album": (
        "ratingKey",
        "type",
        "title",
    ),
    "artist": (
        "ratingKey",
        "type",
        "title",
    ),
    "playlist": (
        "ratingKey",
        "type",
        "title",
    ),
}


def _element(kind: str, attributes: dict) -> dict:
    unknown = sorted(set(attributes) - set(ATTRIBUTES[kind]))
    if unknown:
        raise KeyError(
            f"{kind}: {unknown} is not an attribute the model declares, and a double may "
            "not invent one; declare it, and the capture check will say whether a real "
            "server sends it"
        )
    absent = [name for name in REQUIRED[kind] if attributes.get(name) in (None, "")]
    if absent:
        raise KeyError(f"{kind}: a real {ELEMENT[kind]} element always carries {absent}")
    return attributes


def track(**attributes) -> dict:
    """The attributes of one Track element, as plex::library::Track declares them."""
    return _element("track", attributes)


def album(**attributes) -> dict:
    """The attributes of one Directory element, as plex::library::Album declares them."""
    return _element("album", attributes)


def artist(**attributes) -> dict:
    """The attributes of one Directory element, as plex::library::Artist declares them."""
    return _element("artist", attributes)


def playlist(**attributes) -> dict:
    """The attributes of one Playlist element, as plex::library::Playlist declares them."""
    return _element("playlist", attributes)
