# @generated by metaobjects (metagen:capture_contract) from the model in metaobjects/.
# Do not edit: change the metadata and regenerate. A hand edit fails
# `metaobjects verify --codegen`.
"""The capture check, as tests: see ``capture_contract`` beside this file."""

from __future__ import annotations

import pytest

from . import capture_contract as contract

ELEMENTS = contract.answers()


@pytest.mark.parametrize("fqn", sorted(contract.DECLARED))
def test_every_declared_attribute_is_one_a_real_server_sent(fqn):
    missing = contract.never_sent(ELEMENTS, {fqn: contract.DECLARED[fqn]})
    assert missing == {}, (
        f"{missing} is declared and no captured answer carries it: it was invented, or it "
        "needs an `unobserved` reason saying why the capture could not have seen it"
    )


@pytest.mark.parametrize("key", sorted(contract.ROWS))
def test_every_attribute_a_row_reads_is_in_each_answer_it_is_built_from(key):
    missing = contract.never_read(ELEMENTS, {key: contract.ROWS[key]})
    assert missing == {}, f"{missing}: the column is empty everywhere but in the tests"
